### ISSUE TITLE
Old sources in npm package 

### ISSUE THREAD

**Issue by airs0urce** [willconant/flow-js#5]
Thank you for the great library.
The only problem there: On npm repository in package.json you have version = 0.2.2, but actually  it's not.
Please check number of lines inside flow.js and test.js files (may be others).
I think version number was updated, but there are old sources in repository!
Thanks!

**Comment by srobbin** [comment]
It's true. The version on NPM is one commit old, before you could pass an identifier to MULTI.

**Comment by jketterl** [comment]
having this problem too. the version in npm basically works, but this.MULTI() does ignore the parameter, and the results array is numeric-only, with the sequence within mostly being random.

can somebody update the npm?

**Comment by raizyr** [comment]
A year later, and the NPM version is still old. :-1:

**Comment by willconant** [comment]
flow@0.2.3 published to npm
